# Generated by Django 4.1.3 on 2022-11-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(default='stories/images/default.jpg', upload_to='stories/images'),
        ),
    ]
