# Generated by Django 4.1.3 on 2022-12-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_alter_story_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
